install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

after_build:
  - cmd: 7z a dotNetRDFToolkitInstaller-%GitVersion_SemVer%.zip %APPVEYOR_BUILD_FOLDER%\ToolkitInstaller\bin\Release\*.*
  - cmd: 7z a dotNetRDFToolkit-noInstaller-%GitVersion_SemVer% %APPVEYOR_BUILD_FOLDER%\ToolkitInstaller\packages
  
configuration: Release

artifacts:
  - path: dotNetRDFToolkitInstaller-$(GitVersion_SemVer).zip
  - path: dotNetRDFToolkit-noInstaller-$(GitVersion_SemVer).zip

deploy:
  - provider: GitHub
    description: 'dotNetRDF.Toolkit $(GitVersion_SemVer)'
    auth_token:
      secure: j1Qanb5R8lGcUc4Drk5Pjk1ra9domw0vA1pbILJBWPQ1r3XAIETCd9L8N6GN2NZbE/aYCEdHjr4VTjfNQB1bKTKcZ4Unux/XuyAwFrzjZHg=
    on:
      appveyor_repo_tag: true 
    artifact: dotNetRDFToolkitInstaller-$(GitVersion_SemVer).zip, dotNetRDFToolkit-noInstaller-$(GitVersion_SemVer).zip
