install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

artifacts:
  - path: ToolkitInstaller\bin\Release
    name: dotNetRDFToolkitInstaller-$(GitVersion_SemVer)
    type: zip
  - path: ToolkitInstaller\packages
    name: dotNetRdfToolkit-noInstaller-$(GitVersion_SemVer)
    type: zip

deploy:
  - provider: GitHub
    description: 'dotNetRDF.Toolkit $(GitVersion_SemVer)'
    auth_token:
      secure: j1Qanb5R8lGcUc4Drk5Pjk1ra9domw0vA1pbILJBWPQ1r3XAIETCd9L8N6GN2NZbE/aYCEdHjr4VTjfNQB1bKTKcZ4Unux/XuyAwFrzjZHg=
    on:
      appveyor_repo_tag: true 
    artifact: dotNetRDFToolkitInstaller-$(GitVersion_SemVer), dotNetRdfToolkit-noInstaller-$(GitVersion_SemVer)
