install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

artifacts:
  - ToolkitInstaller\bin\Release\dotNetRdf-Toolkit.msi
  - ToolkitInstaller\bin\Release\setup.exe