install:
  - choco install gitversion.portable -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

after_build:
  - cmd: 7z a dotNetRDFToolkitInstaller-%GitVersion_SemVer%.zip %APPVEYOR_BUILD_FOLDER%\ToolkitInstaller\bin\Release\*.*
  - cmd: 7z a dotNetRDFToolkit-noInstaller-%GitVersion_SemVer%.zip %APPVEYOR_BUILD_FOLDER%\ToolkitInstaller\packages\* -xr!info
  - cmd: 7z a dotNetRDFToolkit-noInstaller-%GitVersion_SemVer%.zip %APPVEYOR_BUILD_FOLDER%\ToolkitInstaller\packages\info\*
  
configuration: Release

artifacts:
  - path: dotNetRDFToolkitInstaller-$(GitVersion_SemVer).zip
  - path: dotNetRDFToolkit-noInstaller-$(GitVersion_SemVer).zip

deploy:
  - provider: GitHub
    description: 'dotNetRDF.Toolkit $(GitVersion_SemVer)'
    auth_token:
      secure: KMC9yx8cu4fyzvtDnRIcmtowLKx9hpAwJhIyz6E4LYj79Rp1BiA7QXuyUZo7xUzm
    on:
      appveyor_repo_tag: true 
    artifact: dotNetRDFToolkitInstaller-$(GitVersion_SemVer).zip, dotNetRDFToolkit-noInstaller-$(GitVersion_SemVer).zip
